### ISSUE TITLE
Klarna order could not be captured

### ISSUE THREAD

**Issue by kvasscom** [vippsas/vipps-woocommerce#69] opened 2021-03-16 13:09 UTC
Hi, a customer of mine has a repeating problem with some of the orders done in their WooCommerce webshop. Some of the orders start out with Vipps as payment method and then it gets an error in the Order notes, stating that Klarna order could not be captured.

I don't know why it suddenly becomes a Klarna order, but is this a regular problem with Vipps or is it a problem with WooCommerce or Klarna?

**It goes something like this:**
1. Vipps payment initiated
2. Awaiting Vipps payment confirmation
3. Vipps callback received
4. Payment authorized at Vipps
5. Stock levels reduced for the product
6. Order status changed from Pending payment to On Hold
7. Order status changed from On Hold to Processing (manually done by staff)
8. Klarna order could not be captured due to an error.
9. Order status changed from Completed to On Hold.

Is it a routine problem done by the staff or is it a bug with the plugin?

I hope to be able to solve this, sincerely Mathias.

**Comment by cloveras** [comment] 2021-03-16 13:43
Hi @mathias94 

I suspect you will get help from the plugin developer here too, but the best placve to get help is: https://wordpress.org/support/plugin/woo-vipps

This is also mentioned here: https://github.com/vippsas/vipps-woocommerce#how-can-i-get-help-if-i-have-any-issues

Christian, Vipps

**Comment by iverok** [comment] 2021-03-16 13:59
> 8. Klarna order could not be captured due to an error.
> 9. Order status changed from Completed to On Hold.
> 
> Is it a routine problem done by the staff or is it a bug with the plugin?

It is not a regular problem; and I would not think that this is a problem with the Vipps plugin, since this does not change the payment method of any orders after it has been created; and in particular, it does not change this payment method to "klarna" of course.   

Could you check that this order really does have "klarna", "kco" or similar as the payment method at this point?

I wonder though - on step 8 and 9 as above, I assume that the order is captured at Vipps (since you went from "on hold" to "processing" manually). Is this the case? Could you press the "get complete transaction details"  for the order (assuming it is still a Vipps order) and check that the payment is completely captured?

The reason I'm asking is that the Vipps plugin does behave as you describe when the order is set to Complete when the payment can't be captured *at Vipps* as an error handling mechanism; I'm not sure if Klarna behaves similarily.

**Comment by kvasscom** [comment] 2021-03-26 12:16
> Could you check that this order really does have "klarna", "kco" or similar as the payment method at this point?

It seems it has actually become a Klarna order at this point, there is no Vipps section at the right sidebar when looking at the order in WooCommerce. Only a section saying "Klarna Order Management" and then within that box it says "Failed to retrieve the order from Klarna".

> I wonder though - on step 8 and 9 as above, I assume that the order is captured at Vipps (since you went from "on hold" to "processing" manually). Is this the case? Could you press the "get complete transaction details" for the order (assuming it is still a Vipps order) and check that the payment is completely captured?

I'm checkin what their routines is, but yes it has been manually changed from "On hold" to "Processing", I'm gonna find out if they checked whether or not it was captured before they did that.

**Comment by iverok** [comment] 2021-03-26 14:03
That is deeply weird. As far as I know, the only way an order changes its payment method is if the customer restarts the order (from the home screen) and chooses a new payment method, which shouldn't be possible with Vipps (because each order-id can only be started once).  

I guess it's possible that some callback from Klarna could change the order; but it seems unlikely.

To re-set the payment method for the order to Vipps (just so it can be completed) it should be enough to set the _payment_method postmeta-key for the order to 'vipps'.

**Comment by tOgg1** [comment] 2021-04-04 09:42
Hi,

We have experienced this exact error, with the same steps 1. - 9. as outlined in the initial post of this thread. The only action taken by a staff member on our site AFAIK is the same (step 7.).

**Comment by iverok** [comment] 2021-04-06 13:58
If you can replicate this somehow, that would help a lot, especially when it comes to determining _when_ the order gets its payment method set to Klarna. If you change the method manually to "vipps", you will be able to see if the order has been captured properly, in which case it would have been after "processing". 

There is really no mechanism for the Vipps plugin to change the payment method to something other than Vipps, but perhaps it may be possible to determine what changes the payment method so that this can be reported to Klarna or whatever mechanism performs it.

**Comment by iverok** [comment] 2022-11-07 15:18
There seems to be some kind of process that sometimes turn "vipps" orders into "kco" orders, but exactly how is still unclear. As the issue is being debugged in another context, we close this issue.

**Closed by iverok** 2022-11-07 15:18 UTC
