### ISSUE TITLE
Possibly problem with unique order id

### ISSUE THREAD

**Issue by orjansteffensen** [vippsas/vipps-woocommerce#37] opened 2020-01-22 07:23 UTC
I noticed this error in the log file for Vipps. There are usually a couple of these errors for each day. We also have some customers who aren't able to fulfill their order, and who are just sent back to cart page instead of order confirmation. Could this error be relevant for the problem?

We're using Klarna Checkout, with Vipps integrated in the Klarna iframe.

`2020-01-18T08:14:17+00:00 ERROR Kunne ikke opprette Vipps-betaling 400 orderId is already used, and must be unique`

![2020-01-22 08_16_33-Window](https://user-images.githubusercontent.com/24268072/72873664-a0741080-3cf0-11ea-9680-c807d726dd68.png)

**Comment by iverok** [comment] 2020-01-22 14:12
The order ID is based on the id of the WC_Order object, and so should be unique for each order. 

 - Are you using the same Vipps account on multiple stores? If so, you *must* use different order-number prefixes on each store instance. These are in the Vipps settings. You should also use different prefixes on Test and Production sites.
- Are you overriding the 'woo_vipps_order_id' filter? If so, the code producing the order id must ensure orders are unique. This filter is for using sequential order numbers or custom order numbers.

When you use a Payment Gateway in WooCommerce, a new order is created each time, so the ID should be unique in all normal cases.

**Comment by orjansteffensen** [comment] 2020-01-27 11:11
No, we're not using the same credentials anywhere else and we're not overriding the filther either.

However, after writing this post I updated the Klarna Checkout plugin to a developer version (https://github.com/krokedil/klarna-checkout-for-woocommerce/tree/develop-v2), and haven't had any more of these errors after that.

Here's a overview of the amount of times I've found the error in the logs.

![2020-01-27 12_04_48-Woo feilmelding - Google Regneark](https://user-images.githubusercontent.com/24268072/73170167-06500600-40fe-11ea-9a4d-88afbac827bd.png)

**Comment by iverok** [comment] 2020-01-27 15:51
Ok - good that it worked out; probably that means that it is possible to re-start a transaction in the old version with an old order ID. It is unfortunately not easy to handle this in the Vipps Gateway.

**Comment by flaritycat** [comment] 2020-03-30 12:23
We still have this issue, and the developer branch (klarna) isn't available any longer? It seems, to be an issue when customers go back and forth, updating the checkout items.

**Comment by iverok** [comment] 2020-03-31 07:19
I see.  Well, they way things are currently, the order object must exist before starting the payment process, and Vipps does not allow restarting this process after initate_payment has been called.  Because of this, I've had to disable the restart processes normally available on the "My page" page, and the order is cancelled on abandoning the order in Vipps. 

It may be that it is somehow possible to restart the order after having been to the Vipps app using the Klarna Checkout system, but I don't really see how.  In particular, if you go "back" from Vipps, the order ought to be cancelled, not get reset to "pending" or "on-hold".

If you have a reproducible case, it may be possible to stop the error from happening, but maybe it would be better to instead try to make restarting the payment possible. It may be possible to steal some digits from the Vipps order number to implement a retry counter. It will make the flowchart much more complicated, but I can look into it. This would mean changing the logic of a non-successful return from Vipps into a "choose other payment option" situation.

On the shorter term, if you can reproduce the case at-will, that will help a lot.

**Comment by flaritycat** [comment] 2020-03-31 17:11
Okay, today we are experiencing a lot of trouble. Customers are having big issues with paying.
The last 4 customers couldn't pay.

There where no answers directly from the Vipps Support Team. 
It seems like the API callback for "APPROVED" isn't being sent from Vipps.
Timeouts for 10 minutes. And we also have customers getting billed by Vipps, but Woocommerce can't tell.

From earlier today:
2020-03-31T15:04:04+00:00 INFO Checking order status on Vipps for order id: 34038
2020-03-31T15:04:04+00:00 INFO order status pending 
2020-03-31T15:04:09+00:00 INFO Checking order status on Vipps for order id: 34038
2020-03-31T15:04:09+00:00 INFO order status pending 
2020-03-31T15:37:54+00:00 ERROR Kunne ikke opprette Vipps-betaling 500 
500 

* I've disabled an autooptimization for the site, checking if this helps.
* I have strict settings for countryblocking, but i reckon Vipss won't use any servers outside Norway.

T

**Comment by flaritycat** [comment] 2020-03-31 17:35
I've tested now, and I can see the message " Noe gikk galt, mottok ikke noen leveringsmetoder".
We don't use an plugin for this, all is set manually.

**Comment by flaritycat** [comment] 2020-03-31 17:45
Update: The issue was the callback for adress. Fixed with using the option" store adress"

**Comment by iverok** [comment] 2020-04-01 07:27
Thank you for the update!  The message you got means, as you discovered, that the shipping callback somehow failed. When it does, and you do not get corresponding log entries in the WC log, it probably means that the callback was never received - otherwise you would have gotten either a fatal error or a log message about there not being any shipping options available.

The payment success callback would have failed similarily, but that would have caused a (more expensive) poll of the Vipps servers after a while, so the error would have been hidden.  Probably normal checkout (not express checkout) would have worked.

**Comment by flaritycat** [comment] 2020-04-02 19:04
Hi, a new update. It seems there is still a few issues.
1. Now, one of the orders got mixed up with klarna.. so Vipps did an API-call for a purchase as well as klarna on the same order.
2. See printscreen for issue. (Im deactivating optimize again, and checking.)
![image](https://user-images.githubusercontent.com/3369890/78291346-868f4f00-7525-11ea-8b4d-13a46ee18fbb.png)

**Comment by iverok** [comment] 2022-11-07 14:56
Original bug should be fixed in 1.11.6, problem was restarting orders using the back-button, which restarted the current order at Vipps causing the 400.

**Closed by iverok** 2022-11-07 14:56 UTC
